In [2]:
import tensorflow as tf
x = tf.constant(35)
y = x+5
print(y)

Tensor("add:0", shape=(), dtype=int32)


In [3]:
print(tf.Session.run(y)) #note wierd API capitlization and cammel case

TypeError: run() missing 1 required positional argument: 'fetches'

In [4]:
sess = tf.Session() #launches graph, sort of like compiling; https://www.tensorflow.org/api_docs/python/tf/Session
print(sess.run(y))

40


In [5]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(y*x))

35
40
1400


In [6]:
"""
with open('output.txt', 'w') as f:
    f.write('Hi there!')
"""

"\nwith open('output.txt', 'w') as f:\n    f.write('Hi there!')\n"

In [7]:
with tf.Session() as sess:
    add=sess.run(tf.add(y,x))
    mul=sess.run(tf.multiply(y,x)) #ALL the math functions are built in, always use the most complex one
    print(add) #note that not assigning before print won't work
    print(mul)

75
1400


In [8]:
matrix1 = tf.constant([[3., 3.]])

In [9]:
#remind you of something?
import numpy as np
a=np.array([[3.,3.]])
print(a)

[[3. 3.]]


In [10]:
matrix2 = tf.constant([[2.],[2.]])

with tf.Session() as sess:
    result = sess.run(tf.matmul(matrix1, matrix2))
    print(result)

[[12.]]


In [15]:
w=tf.Variable(3.) #note float/int infered in compilation
with tf.Session() as sess:
    result = w.assign_add(1.)
    print(result)

Tensor("AssignAdd_1:0", shape=(), dtype=int32_ref)


In [17]:
w=tf.Variable(3.) #note float/int infered in compilation
with tf.Session() as sess:
    sess.run(w.initializer) #note this
    result = sess.run(w.assign_add(1.))
    print(result)

4.0


In [19]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) #note this
    result = sess.run(w.assign_add(1.))
    print(result)

4.0


In [21]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
      print(sess.run(y))  # ERROR: will fail because x was not fed.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float and shape [1024,1024]
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_1', defined at:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-da4e5cb75990>", line 1, in <module>
    x = tf.placeholder(tf.float32, shape=(1024, 1024))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype float and shape [1024,1024]
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_FLOAT, shape=[1024,1024], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [22]:
with tf.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x: rand_array})) 

[[241.58177 244.36314 249.88052 ... 248.94089 248.72318 245.17667]
 [244.50217 245.51744 250.18166 ... 247.42949 247.33333 245.96568]
 [255.59631 258.62726 267.6002  ... 259.7955  263.7267  263.89972]
 ...
 [254.36984 253.87463 261.0693  ... 255.8068  262.53363 256.60715]
 [247.00702 250.69281 250.50543 ... 251.48593 255.74336 254.20198]
 [245.94107 250.79092 258.56897 ... 253.53012 258.43793 252.53284]]


In [ ]:
# https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/3_NeuralNetworks/neural_network_raw.ipynb